# Generated by Django 5.1.5 on 2025-02-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
