# Generated by Django 5.1.5 on 2025-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlistitem_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='item_name',
            field=models.CharField(max_length=400),
        ),
    ]
