# Generated by Django 5.1.5 on 2025-02-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_alter_wishlistitem_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
